### ISSUE TITLE
Error with minimiro using rustybam

### ISSUE THREAD

**Issue by Rafaelsoler13** [mrvollger/minimiro#5]
Hello,

I am trying to cut a PAF file to substract specific coords and plot them using minimiro. However, when I tried to plot it, it gives me this error message:

```
python3 ~/minimiro.py --paf chr8_trimmed.paf --bestn 1000 -o chr8_trimmed.ps && ps2pdf chr8_trimmed.ps
Traceback (most recent call last):
  File "~/minimiro.py", line 216, in <module>
    cs = re.match(f"{args.cigar}:Z:(\S+)", row["cs"])
  File "/usr/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

There were analyzed like this

```
/minimap2-2.17/minimap2 -c --eqx -s 200000 -p 0.01 -N 1000 --cs chr8_hg38.fa chr8_CHM13v1.fa > chr8_test_cigar.paf
rustybam liftover --bed <(printf "chr8\t6545299\t13033398\n") chr8_test_cigar.paf > chr8_trimmed_cigar.paf
python3 ~/minimiro.py --paf chr8_trimmed_cigar.paf --bestn 1000 -o chr8_trimmed.ps && ps2pdf chr8_trimmed.ps
```

I attached you the files:

[chr8_test_cigar.paf.txt](https://github.com/mrvollger/minimiro/files/11312685/chr8_test_cigar.paf.txt)
[chr8_trimmed_cigar.paf.txt](https://github.com/mrvollger/minimiro/files/11312671/chr8_trimmed_cigar.paf.txt)

In addition to that, is the minimap2 output necessary to be in CIGAR format?

Thanks!

**Comment by mrvollger** [comment]
I rewrote minimiro as SafFire to work better with rustybam:
https://github.com/mrvollger/SafFire
But if you want to use minimiro make the paf with the CIGAR and --eqx and and then run minimiro with the cigar option:
```--cigar cg```
https://github.com/mrvollger/minimiro/blob/8a77b2505fa97cecf841eb76e3c73317a2162fec/minimiro.py#LL38C1-L38C1

**Comment by Rafaelsoler13** [comment]
Hello @mrvollger 

Thanks for the answer! However, I am having another problem. I am trying to cut a paf file using rustybam and plot it with minimiro. I aligned the ChrX of Human hg38 and Gorilla ChrX GorGor6 with minimap2:

/home/victor/Documentos/minimap2/minimap2 -c --eqx -p 0.01 -N 1000 --cs Gorilla_ChrX.fasta Human_ChrX.fasta > ChrX.paf

An after that, I cut it with rustybam:

rustybam liftover --bed <(printf "gorGor6_dna_ChrX\t67510894\t68060894\n") ChrX.paf > chrX_trimmed.paf

[chrX_trimmed.paf.txt](https://github.com/mrvollger/minimiro/files/11404895/chrX_trimmed.paf.txt)

But when I try to aligned with minimiro, it gives me this error:

```
python3 /home/rso12/Escritorio/syntenic_plot/minimiro/minimiro.py --paf chrX_trimmed.paf --bestn 1000 --cigar cg -o chrX_trimmed.paf && ps2pdf chrX_trimmed.paf
Traceback (most recent call last):
  File "/home/rso12/Escritorio/syntenic_plot/minimiro/minimiro.py", line 480, in <module>
    rightmost = max(contigs["len"])
ValueError: max() arg is an empty sequence
```

However, I did a test with a smaller alignment, and actually it worked:

```
minimap2 -c --eqx -p 0.01 -N 1000 --secondary=no --cs gorilla_test_apes_1.fasta human_test_apes_1.fasta > greats_apes_test_3_cigar.paf
python3 /home/rso12/Escritorio/syntenic_plot/minimiro/minimiro.py --paf greats_apes_test_3_cigar.paf --bestn 1000 -o greats_apes_test_3_cigar.ps && ps2pdf greats_apes_test_3_cigar.ps
rustybam liftover --bed <(printf "gorGor6_dna\t10738\t15738\n") greats_apes_test_3_cigar.paf > greats_apes_test_3_cigar_trimmed.paf
python3 /home/rso12/Escritorio/syntenic_plot/minimiro/minimiro.py --paf greats_apes_test_3_cigar_trimmed.paf --cigar cg --bestn 1000 -o greats_apes_test_3_cigar_trimmed.ps && ps2pdf greats_apes_test_3_cigar_trimmed.ps
```

[minimiro_question.tar.gz](https://github.com/mrvollger/minimiro/files/11404931/minimiro_question.tar.gz)

What can be happening? Thanks!

**Comment by Rafaelsoler13** [comment]
Hello @mrvollger 

Thanks for the answer! I am trying to align the Human and Gorilla chrX, cut it with rustybam with specific coordinates, and plot it with minimiro. However, when I try to plot it, the x-axis is not zoomed in and it keeps the previous x-axis size.

[ChrX.pdf](https://github.com/mrvollger/minimiro/files/11405916/ChrX.pdf)
[chrX_trimmed.pdf](https://github.com/mrvollger/minimiro/files/11405917/chrX_trimmed.pdf)

So the plot is too small. What can I do to replicate the plot that it is created when I do the alignment of an specific chromosome zone and I plot it?

**Comment by Rafaelsoler13** [comment]
I think it is due to using the total length as x-axis instead of using the sequence end - sequence start to plot it, so when the rusty bam cut the alignment, even if you try to align it with minimiro, it still uses the total alignment length. How can I solve this to plot with the corresponding zoom after Rustybam cut using minimiro?

Best regards and thanks,

Rafael
